// biome-ignore-all lint/style/noNonNullAssertion: coverage harness
// biome-ignore-all format: compact for 400 budget
import { describe, expect, test } from "bun:test"
import { mkdtempSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { NAV } from "../src/tokenmeter/browser/constants"
import { showProjectDetail } from "../src/tokenmeter/browser/project-dialog"
import { showSessionDetail } from "../src/tokenmeter/browser/session-dialog"
import { clearPricing } from "../src/tokenmeter/pricing"
import { __setPricingFetchForTest, clearRemotePricing } from "../src/tokenmeter/pricing-remote"

function stubPricing(){ clearPricing(); clearRemotePricing(); __setPricingFetchForTest((async () => ({ ok: true, json: async () => ({}) } as unknown as Response)) as unknown as typeof fetch) }
function host(){let s:{r:()=>unknown;c?:()=>void}[]=[];let rc=0,cc=0,cap:any=null,oc=0;const dlg={replace(r:()=>unknown,c?:()=>void){rc++;s=[{r,c}]},clear(){const cs=s.map(x=>x.c).filter(Boolean) as (()=>void)[];const had=s.length>0;s=[];if(had)cc++;for(const f of cs){try{oc++;f()}catch{}}}} as any;const get=()=>{if(!s[0])throw new Error("no render");(s[0].r as ()=>unknown)();const v=cap!;cap=null;return v as {title:string;options:{title:string;value:string;category?:string;description?:string}[];onSelect?:(v:any)=>void}};const capF=(p:any)=>{cap=p;return null as any};return {dlg,get,capF,rc:()=>rc,cc:()=>cc,oc:()=>oc}}
function mkProjectHarness(o:Partial<{sessions:unknown[];fail:boolean;empty:boolean;noCurrent:boolean}>={}){ stubPricing(); const d=mkdtempSync(join(tmpdir(),"tm-pd-"));const h=mkdtempSync(join(tmpdir(),"tm-ph-"));const w=mkdtempSync(join(tmpdir(),"tm-pw-"));const proj=[{id:"projA",name:"alpha",worktree:w,time:{created:1700000000000,updated:1700000005000}}];const ho=host();let sess:unknown[];if(o.empty) sess=[];else if(o.sessions) sess=o.sessions;else sess=o.noCurrent?[{id:"s1",title:"one",time:{created:1,updated:2},parentID:null,tokens:{input:5,output:5,cache:{read:0,write:0}},cost:0.05,model:{providerID:"openai",id:"gpt-4o"}},{id:"s2",title:"two",time:{created:2,updated:5},parentID:null,tokens:{input:10,output:5,cache:{read:0,write:0}},cost:0.1,model:{providerID:"openai",id:"gpt-4o"}}]:[{id:"s1",title:"one",time:{created:1,updated:5},parentID:null,tokens:{input:10,output:5,cache:{read:0,write:0}},cost:0.1,model:{providerID:"openai",id:"gpt-4o"}},{id:"s2",title:"two",time:{created:2,updated:4},parentID:null,tokens:{input:5,output:5,cache:{read:0,write:0}},cost:0.05,model:{providerID:"openai",id:"gpt-4o"}}];const api={state:{path:{directory:h,state:d}},client:{project:{list:async()=>({data:proj}) as never,current:async()=>({data:{id:o.noCurrent?"other": "projA"}}) as never,directories:async()=>({data:[]}) as never},session:{list:async(p:Record<string,unknown>)=>{if(o.fail) throw new Error("fail"); const dir=p.directory as string; if(dir===w) return {data:sess} as never; return {data:[]} as never},get:async()=>({data:{id:"s1",projectID:"projA"}}) as never,messages:async()=>({data:[]}) as never,children:async()=>({data:[]}) as never},model:{list:async()=>({data:[]})},v2:{model:{list:async()=>({data:[]})},session:{list:async()=>({data:[]})}}},route:{current:{params:{sessionID:o.noCurrent? "other":"s1"}}},currentSessionID:o.noCurrent? "other":"s1",ui:{dialog:ho.dlg,DialogSelect:ho.capF,toast(){}}};return {api:api as never,ho,d,h,w,cleanup(){for(const x of [d,h,w]) try{rmSync(x,{recursive:true,force:true})}catch{}}}}
function mkSessionHarness(o:Partial<{msgs:unknown[];fail:boolean}>= {}){ stubPricing(); const d=mkdtempSync(join(tmpdir(),"tm-sd-"));const h=mkdtempSync(join(tmpdir(),"tm-sh-"));const ho=host();const msgs=o.msgs??[];const api={state:{path:{directory:h,state:d}},client:{project:{list:async()=>({data:[{id:"projA",name:"alpha",worktree:h,time:{created:1,updated:2}}]}) as never,current:async()=>({data:{id:"projA"}}) as never,directories:async()=>({data:[]}) as never},session:{list:async()=>({data:[]}) as never,get:async(p:Record<string,unknown>)=>{if(o.fail) throw new Error("fail"); return {data:{id:p.sessionID,projectID:"projA",title:"Alpha",time:{created:1000,updated:2000},tokens:{input:0,output:0,cache:{read:0,write:0}},cost:0}} as never},messages:async(p:Record<string,unknown>)=>({data:(msgs as any[]).filter((m:any)=>m.sessionID===p.sessionID).map((m:any)=>({info:m}))}) as never,children:async()=>({data:[]}) as never},model:{list:async()=>({data:[]})},v2:{model:{list:async()=>({data:[]})},session:{list:async()=>({data:[]})}}},route:{current:{params:{sessionID:"s1"}}},currentSessionID:"s1",ui:{dialog:ho.dlg,DialogSelect:ho.capF,toast(){}}};return {api:api as never,ho,d,h,cleanup(){for(const x of [d,h]) try{rmSync(x,{recursive:true,force:true})}catch{}}}}
function mkMsg(id:string,sid:string,prov:string,model:string,i:number,o:number,cost:number){return {id,sessionID:sid,role:"assistant",providerID:prov,modelID:model,cost,tokens:{input:i,output:o,reasoning:0,cache:{read:0,write:0}}}}
describe("browser dialog coverage: project/session",()=>{
test("project loading → error → empty → populated",async()=>{let h=mkProjectHarness();showProjectDetail(h.api,"projA");let lo=h.ho.get();expect(lo.title).toContain("loading");expect(lo.options[0]!.value).toBe("__loading");h.cleanup();h=mkProjectHarness({fail:true});showProjectDetail(h.api,"projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.options[0]!.value).toBe("__error");expect(lo.options.some(o=>o.value==="__back"&&o.category===NAV)).toBe(true);h.cleanup();h=mkProjectHarness({empty:true});showProjectDetail(h.api,"projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.options.some(o=>o.value==="__empty")).toBe(true);expect(lo.options.some(o=>o.value==="__back")).toBe(true);expect(lo.title).toContain("alpha");h.cleanup();h=mkProjectHarness();showProjectDetail(h.api,"projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.title).toContain("(2)");expect(lo.options.some(o=>o.value==="s1"&&o.category==="Current Session")).toBe(true);expect(lo.options.some(o=>o.value==="s2"&&o.category==="Sessions")).toBe(true);h.cleanup();h=mkProjectHarness({noCurrent:true});showProjectDetail(h.api,"projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.options.filter(o=>o.category==="Sessions").length).toBeGreaterThan(0);h.cleanup()})
test("project onSelect guards and navigation",async()=>{const h=mkProjectHarness();showProjectDetail(h.api,"projA");await new Promise(r=>setTimeout(r,600));const lo=h.ho.get() as any;const before=h.ho.rc();lo.onSelect(null);expect(h.ho.rc()).toBe(before);lo.onSelect({title:"",value:"__loading"});expect(h.ho.rc()).toBe(before);lo.onSelect({title:"",value:"__period"});expect(h.ho.rc()).toBe(before);const closeOpt=lo.options.find((o:any)=>o.value==="__close")!;lo.onSelect({title:"",value:"__close"});expect(h.ho.cc()).toBe(1);lo.onSelect({title:"",value:"__close"});expect(h.ho.cc()).toBe(1);h.cleanup();const h2=mkProjectHarness();showProjectDetail(h2.api,"projA");await new Promise(r=>setTimeout(r,600));const lo2=h2.ho.get() as any;lo2.onSelect({title:"",value:"__back"});await new Promise(r=>setTimeout(r,300));expect(h2.ho.rc()).toBeGreaterThan(2);h2.cleanup();const h3=mkProjectHarness();showProjectDetail(h3.api,"projA");await new Promise(r=>setTimeout(r,600));const lo3=h3.ho.get() as any;const sOpt=lo3.options.find((o:any)=>o.value==="s1")!;expect(sOpt).toBeDefined();lo3.onSelect({title:sOpt.title,value:sOpt.value});await new Promise(r=>setTimeout(r,600));expect(h3.ho.rc()).toBeGreaterThan(3);const after=h3.ho.get();expect(after.options.some((o:any)=>o.value==="__back")).toBe(true);h3.cleanup()})
test("session loading → error → overview",async()=>{let h=mkSessionHarness();showSessionDetail(h.api,"s1","projA");let lo=h.ho.get();expect(lo.title).toContain("loading");expect(lo.options[0]!.value).toBe("__loading");h.cleanup();h=mkSessionHarness();showSessionDetail(h.api,"" as any,"projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.options[0]!.value).toBe("__error");expect(lo.options.some(o=>o.value==="__back")).toBe(true);h.cleanup();h=mkSessionHarness();showSessionDetail(h.api,"s1","projA");await new Promise(r=>setTimeout(r,600));lo=h.ho.get();expect(lo.options.some(o=>o.value==="__messages")).toBe(true);expect(lo.options.some(o=>o.value==="__back")).toBe(true);h.cleanup()})
test("session with providers and models",async()=>{const msgs=[mkMsg("m1","s1","openai","openai/gpt-4o",1000,500,0.2),mkMsg("m2","s1","anthropic","anthropic/claude",500,300,0.15)];const h=mkSessionHarness({msgs});showSessionDetail(h.api,"s1","projA");await new Promise(r=>setTimeout(r,600));const lo=h.ho.get();expect(lo.options.some(o=>o.value.startsWith("__prov:"))).toBe(true);expect(lo.options.some(o=>o.value.startsWith("__mod:"))).toBe(true);expect(lo.title).toContain("Alpha");h.cleanup()})
test("session onSelect guards, Back with/without hint, Close once",async()=>{const h=mkSessionHarness();showSessionDetail(h.api,"s1","projA");await new Promise(r=>setTimeout(r,600));const lo=h.ho.get() as any;const before=h.ho.rc();lo.onSelect(null);expect(h.ho.rc()).toBe(before);lo.onSelect({title:"",value:"__loading"});expect(h.ho.rc()).toBe(before);lo.onSelect({title:"",value:"__prov:openai"});expect(h.ho.rc()).toBe(before);const closeOpt=lo.options.find((o:any)=>o.value==="__close")!;lo.onSelect({title:"",value:"__close"});expect(h.ho.cc()).toBe(1);lo.onSelect({title:"",value:"__close"});expect(h.ho.cc()).toBe(1);h.cleanup();const h2=mkSessionHarness();showSessionDetail(h2.api,"s1","projA");await new Promise(r=>setTimeout(r,600));const lo2=h2.ho.get() as any;lo2.onSelect({title:"",value:"__back"});await new Promise(r=>setTimeout(r,600));expect(h2.ho.rc()).toBeGreaterThan(2);expect(h2.ho.get().options.some((o:any)=>o.value==="__back")).toBe(true);h2.cleanup();const h3=mkSessionHarness();showSessionDetail(h3.api,"s1");await new Promise(r=>setTimeout(r,600));const lo3=h3.ho.get() as any;lo3.onSelect({title:"",value:"__back"});await new Promise(r=>setTimeout(r,300));expect(h3.ho.rc()).toBeGreaterThan(2);h3.cleanup()})
})
