// biome-ignore-all lint/style/noNonNullAssertion: compact harness
// biome-ignore-all format: compact for 400 budget
import { describe, expect, test } from "bun:test"
import { mkdtempSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { NAV } from "../src/tokenmeter/browser/constants"
import { dirExists, iso, navCategory, overviewRows } from "../src/tokenmeter/browser/dialog-shared"
import { showBrowserDialog } from "../src/tokenmeter/browser/projects-dialog"
import { loadSettings, SETTINGS_KV_KEY } from "../src/tokenmeter/settings"

function ensureGit(p:string){ try{ const {mkdirSync}=require("node:fs") as typeof import("node:fs"); const {join}=require("node:path") as typeof import("node:path"); mkdirSync(join(p,".git"),{recursive:true})}catch{} }
function kv(o: Record<string, unknown> = {}){ const m=new Map(Object.entries(o)); return { ready:true, get:(k:string,d?:unknown)=>(m.has(k)?m.get(k):d) as never, set(k:string,v:unknown){m.set(k,v)}}}
function harness(o: Partial<{ projects: unknown[]; currentID: string | null; fail: boolean; empty: boolean; bad: boolean; sessionMap: Record<string, unknown[]> }>) { let render: (()=>unknown)|null=null; let cap: {title:string; options:{title:string;value:string;category?:string;description?:string}[]; onSelect?:(v:{title:string;value:string})=>void}|null=null; let rc=0; let cc=0; const dir=mkdtempSync(join(tmpdir(),"tm-bdp-")); const host=mkdtempSync(join(tmpdir(),"tm-host-")); ensureGit(host); const a=mkdtempSync(join(tmpdir(),"tm-a-")); ensureGit(a); const b=mkdtempSync(join(tmpdir(),"tm-b-")); ensureGit(b); const defaults=[{id:"projA",name:"alpha",worktree:a,time:{created:1700000000000,updated:1700000005000}},{id:"projB",name:undefined,worktree:b,time:{created:1700000000000,updated:1700000008000}}]; const projects=o.empty?[]:o.projects??defaults; const cur=o.currentID??"projA"; const dirMap=o.sessionMap??{[a]:[{id:"s1"}],[b]:[{id:"s2"}],[host]:[{id:"s1"}]}; const projMap:Record<string,unknown[]>={}; for(const p of (projects as Array<{id:string;worktree?:string}>)){ const wt=(p as {worktree?:string}).worktree; if(wt && dirMap[wt]) projMap[p.id]=dirMap[wt]; } if(o.sessionMap){ for(const [k,v] of Object.entries(o.sessionMap)){ if(typeof k==="string" && !k.startsWith("/tmp") && !k.startsWith("/nope")) projMap[k]=v; } } const api={ state:{path:{directory:host,state:dir}}, client:{ project:{ list:async()=>{if(o.fail)throw new Error("fail"); if(o.bad) return {data:"bad"} as never; return {data:projects} as never}, current:async()=>({data:{id:cur}}) as never}, session:{ list:async()=>({data:[]}) as never}, v2:{ session:{ list:async(p:Record<string,unknown>)=>{ const pid=p.project as string; if(pid && projMap[pid]) return {data:projMap[pid]} as never; const d=p.directory as string; if(d&&dirMap[d]) return {data:dirMap[d]} as never; return {data:[]} as never } }}}, ui:{ dialog:{replace(r:()=>unknown){rc++;render=r},clear(){cc++}}, DialogSelect:(props:never)=>{cap=props as never; return null as never}, toast(){}}}; const get=()=>{if(!render)throw new Error("no render"); (render as ()=>unknown)(); const v=cap!; cap=null; return v as {title:string; options:{title:string;value:string;category?:string;description?:string}[]; onSelect?:(v:{title:string;value:string})=>void}}; return {api:api as never,get,rc:()=>rc,cc:()=>cc,cleanup(){for(const d of [dir,host,a,b])try{rmSync(d,{recursive:true,force:true})}catch{}}}}
describe("dialog-shared", () => { test("iso dirExists navCategory overviewRows", () => { expect(iso(1700000000000)).toBe("2023-11-14"); expect(iso(Number.NaN)).toBe("—"); expect(dirExists(null as unknown as string)).toBe(false); expect(dirExists("/tmp")).toBe(true); expect(dirExists("/no-such-xyz-123")).toBe(false); expect(navCategory).toBe(NAV); loadSettings({kv:kv()} as never); const u={context:100,cost:1,input:10,output:20,reasoning:5,cacheRead:2,cacheWrite:3}; const c=overviewRows(u); expect(c.length).toBe(3); expect(c[0]!.value).toBe("__total"); loadSettings({kv:kv({[SETTINGS_KV_KEY]:{numbers:"precise"}})} as never); const p=overviewRows(u); expect(p.length).toBe(5); expect(p[1]!.value).toBe("__input"); loadSettings({kv:kv()} as never) }) })
describe("projects-dialog", () => { test("loading → list with Current pinned", async () => { const h=harness({}); showBrowserDialog(h.api); expect(h.rc()).toBe(1); expect(h.get().title).toContain("loading"); await new Promise(r=>setTimeout(r,30)); const lo=h.get(); expect(lo.title).toBe("TokenMeter: Browse Usage (2)"); expect(lo.options.find(o=>o.category==="Current Project")!.value).toBe("projA"); expect(lo.options.find(o=>o.category==="Current Project")!.title.startsWith("★")).toBe(true); expect(lo.options.some(o=>o.value==="__close"&&o.category===NAV)).toBe(true); h.cleanup() })
test("empty and error", async () => { const e=harness({empty:true}); showBrowserDialog(e.api); await new Promise(r=>setTimeout(r,30)); expect(e.get().options[0]!.title).toBe("No projects found"); e.cleanup(); const f=harness({fail:true}); showBrowserDialog(f.api); await new Promise(r=>setTimeout(r,30)); expect(f.get().options[0]!.title).toBe("Unable to load projects"); f.cleanup() })
test("filters unsafe but keeps zero-session eligible", async () => { const a=mkdtempSync(join(tmpdir(),"tm-fa-")); const b=mkdtempSync(join(tmpdir(),"tm-fb-")); ensureGit(a); ensureGit(b); const h=harness({projects:[{id:"good",name:"good",worktree:a,time:{created:1,updated:2}},{id:"bad",name:"bad",worktree:"/nope-xyz",time:{created:1,updated:3}},{id:"empty",name:"empty",worktree:b,time:{created:1,updated:4}}],currentID:"good",sessionMap:{[a]:[{id:"s1"}],[b]:[]}}); showBrowserDialog(h.api); await new Promise(r=>setTimeout(r,30)); const lo=h.get(); expect(lo.title).toBe("TokenMeter: Browse Usage (2)"); expect(lo.options.some(o=>o.value==="good")).toBe(true); expect(lo.options.some(o=>o.value==="bad")).toBe(false); expect(lo.options.some(o=>o.value==="empty")).toBe(true); h.cleanup(); try{rmSync(a,{recursive:true,force:true})}catch{}; try{rmSync(b,{recursive:true,force:true})}catch{} })
test("remaining branches: no current, zero time, onSelect guards and bad list", async () => { const a=mkdtempSync(join(tmpdir(),"tm-ra-")); ensureGit(a); const b=mkdtempSync(join(tmpdir(),"tm-rb-")); ensureGit(b); const h=harness({projects:[{id:"x",name:"x",worktree:a,time:{created:1,updated:0}},{id:"y",name:"y",worktree:b,time:{created:1,updated:0}}],currentID:"nope",sessionMap:{[a]:[{id:"s1"}],[b]:[{id:"s2"}]}}); showBrowserDialog(h.api); await new Promise(r=>setTimeout(r,30)); const lo=h.get(); expect(lo.options.filter(o=>o.category==="Projects").length).toBeGreaterThan(0); expect(lo.options.find(o=>o.value==="x")!.description).toBe("—"); const sel=lo as {onSelect?:(v:{value:string})=>void}; const before=h.rc(); sel.onSelect?.({title:"",value:"__loading"} as never); expect(h.rc()).toBe(before); sel.onSelect?.(null as never); expect(h.rc()).toBe(before); sel.onSelect?.({title:"x",value:"__close"} as never); expect(h.cc()).toBe(1); h.cleanup(); try{rmSync(a,{recursive:true,force:true})}catch{}; try{rmSync(b,{recursive:true,force:true})}catch{}; const bad=harness({bad:true}); showBrowserDialog(bad.api); await new Promise(r=>setTimeout(r,30)); expect(bad.get().options[0]!.title).toBe("Unable to load projects"); bad.cleanup() }) })
